/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hqyj_dev_procedurem4_modules_Operations_NativieOperate */

#ifndef _Included_com_hqyj_dev_procedurem4_modules_Operations_NativieOperate
#define _Included_com_hqyj_dev_procedurem4_modules_Operations_NativieOperate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hqyj_dev_procedurem4_modules_Operations_NativieOperate
 * Method:    writeModule
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hqyj_dev_procedurem4_modules_Operations_NativieOperate_writeModule
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_hqyj_dev_procedurem4_modules_Operations_NativieOperate
 * Method:    readModule
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hqyj_dev_procedurem4_modules_Operations_NativieOperate_readModule
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
